"""
1. Write a Python program to demonstrate the creation of variables and different data types.

        the program to demonstrate use to indentation,creation,vairables and data type.
"""


"""cerat vairable
variabl is name which can store a value  
        we can use vairable any where in program
"""
 

# Integer data type
age = 21 
print(age)  

# Float data type
height = 6.2 
print( height)  

# String data type
name = "yuvi"  
print("Name:", name)  

# Boolean data type
flag = True  
print(flag) 
" This Is boolean Value:"

#data type 
"""
-in a python many types of data type 
1) Numeric Data type
2) string 
3) boolen 
"""


